# Generated by Django 3.1.2 on 2020-12-09 15:59

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=web.models.galPath)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('moto', models.CharField(max_length=300)),
                ('image', models.FileField(upload_to=web.models.logoPath)),
                ('mission', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=web.models.logoPath)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('head3', models.CharField(max_length=64)),
                ('text3', models.TextField()),
                ('head4', models.CharField(max_length=64)),
                ('text4', models.TextField()),
                ('head5', models.CharField(max_length=64)),
                ('text5', models.TextField()),
                ('text6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=web.models.logoPath)),
            ],
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image1', models.FileField(upload_to=web.models.logoPath)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('head3', models.CharField(max_length=64)),
                ('text3', models.TextField()),
                ('image3', models.FileField(upload_to=web.models.logoPath)),
                ('head4', models.CharField(max_length=64)),
                ('text4', models.TextField()),
                ('image4', models.FileField(upload_to=web.models.logoPath)),
                ('head5', models.CharField(max_length=64)),
                ('text5', models.TextField()),
                ('image5', models.FileField(upload_to=web.models.logoPath)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=64)),
                ('text1', models.TextField()),
                ('image1', models.FileField(upload_to=web.models.logoPath)),
                ('head2', models.CharField(max_length=64)),
                ('text2', models.TextField()),
                ('image2', models.FileField(upload_to=web.models.logoPath)),
                ('head3', models.CharField(max_length=64)),
                ('text3', models.TextField()),
                ('image3', models.FileField(upload_to=web.models.logoPath)),
                ('head4', models.CharField(max_length=64)),
                ('text4', models.TextField()),
                ('image4', models.FileField(upload_to=web.models.logoPath)),
                ('head5', models.CharField(max_length=64)),
                ('text5', models.TextField()),
                ('image5', models.FileField(upload_to=web.models.logoPath)),
            ],
        ),
        migrations.CreateModel(
            name='Tm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=web.models.logoPath)),
            ],
        ),
    ]
