# Generated by Django 3.1.2 on 2020-12-09 22:59

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desg', models.CharField(max_length=100)),
                ('quali', models.TextField()),
                ('image', models.FileField(upload_to=web.models.ProfilePath)),
            ],
        ),
    ]
