# Generated by Django 3.1.2 on 2020-12-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201209_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='facebook',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='twitter',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
