# Generated by Django 3.1.2 on 2020-12-10 04:05

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201210_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodology',
            name='image1',
            field=models.FileField(blank=True, upload_to=web.models.logoPath),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='image3',
            field=models.FileField(blank=True, upload_to=web.models.logoPath),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='image4',
            field=models.FileField(blank=True, upload_to=web.models.logoPath),
        ),
        migrations.AlterField(
            model_name='methodology',
            name='image5',
            field=models.FileField(blank=True, upload_to=web.models.logoPath),
        ),
    ]
