# Generated by Django 3.1.2 on 2020-12-10 15:22

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20201210_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('insta', models.URLField()),
                ('twitter', models.URLField()),
                ('linkd', models.URLField()),
                ('galeryheight', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.FileField(blank=True, upload_to=web.models.logoPath),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, upload_to=web.models.logoPath),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, upload_to=web.models.logoPath),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.FileField(blank=True, upload_to=web.models.logoPath),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.FileField(blank=True, upload_to=web.models.logoPath),
        ),
    ]
