# Generated by Django 3.1.2 on 2020-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20201210_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='facebook',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='insta',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='linkd',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='twitter',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
