# Generated by Django 3.1.2 on 2020-12-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201210_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='galeryheight',
        ),
    ]
