# Generated by Django 3.1.2 on 2020-12-10 17:39

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20201210_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, upload_to=web.models.ProfilePath),
        ),
    ]
